# Generated by Django 2.2 on 2019-04-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jica', '0002_harvest_officer_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('birth_year', models.IntegerField(verbose_name='Birth Year')),
                ('marriage', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('ENGAGED', 'ENGAGED')], max_length=50)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('lUGANDA', 'LUGANDA'), ('RUTOORO', 'RUTORO')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to=None)),
                ('community_status', models.BooleanField(verbose_name='Community Status')),
                ('instructor_possibility', models.BooleanField(verbose_name='Instructor Possibility')),
                ('farm_area', models.CharField(max_length=50)),
                ('crop_type', models.CharField(max_length=50)),
                ('past_harvests', models.CharField(choices=[('DRY', 'DRY'), ('WET', 'WET')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Longitude')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jica.District', verbose_name='District.id')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jica.Parish', verbose_name='Parish.name')),
                ('subcounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jica.Subcounty', verbose_name='Subcounty.id')),
            ],
        ),
    ]
